version: '3'
services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - .:/data
    environment:
 #     - FORCE_SSL=docuseal.sidewayssystems.co.uk
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    networks:
      - traefik
      - docuseal
  postgres:
    image: postgres:15
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal